import {TEST_MODE} from 'env';

export const HOURS_PER_PERIOD = 24;
export const EXPOSURE_NOTIFICATION_CYCLE = 14;
export const MINIMUM_REMINDER_INTERVAL_MINUTES = 180;
export const MIN_OUTBREAKS_CHECK_MINUTES = TEST_MODE ? 15 : 240;
export const CHECKIN_NOTIFICATION_CYCLE = 28;
export const OUTBREAK_NOTIFICATION_CYCLE = 14;
