require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.5'

target 'CovidShield' do
  use_unimodules!(exclude: ['unimodules-face-detector-interface'])
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  target 'CovidShieldTests' do
    inherit! :complete
    # Pods for testing
  end
end
