fastlane_version '2.53.1'

before_all do
  # Load root-level .env to avoid duplication
  Dotenv.overload '../.env'
end

desc "Creates a Github Release"
lane :create_github_release do |options|
  set_github_release(
    repository_name: "cds-snc/covid-shield-mobile",
    api_token: ENV["GITHUB_TOKEN"],
    name: "#{options[:platform]}  v#{ENV['APP_VERSION_NAME']} (#{ENV['APP_VERSION_CODE']})",
    tag_name: "#{options[:platform]}-v#{ENV['APP_VERSION_NAME']}-#{ENV['APP_VERSION_CODE']}",

    description: default_changelog,
    commitish: "master",
  )
end

desc "Returns a default changelog."
lane :default_changelog do
  changelog = changelog_from_git_commits(
    merge_commit_filtering: "only_include_merges",
    pretty: "- %b [%s]"
  ),
  Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
  puts changelog
  changelog.join(' ')
end

platform :ios do
  desc "Submit a new Covid Alert beta build to Apple TestFlight"
  lane :beta do
    ensure_git_branch

    get_certificates(
      output_path: "fastlane/certs"
    )
    get_provisioning_profile(
      output_path: "fastlane/certs"
    )

    build_app(
      scheme: "CovidShield",
      workspace: "./ios/CovidShield.xcworkspace",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV["APP_ID_IOS"] => ENV["PROFILE"]
        }
      }
    )

    groups = ENV["TEST_GROUPS"].split(",")
    upload_to_testflight(
      groups: groups,
      changelog: default_changelog,
      app_version: ENV["APP_VERSION_NAME"],
      build_number: ENV["APP_VERSION_CODE"],
    )

    create_github_release(platform: 'iOS')
  end

  desc "Builds a local iOS adhoc .ipa"
  lane :local do
    get_certificates(
      output_path: "fastlane/certs"
    )
    get_provisioning_profile(
      adhoc: true,
      provisioning_name: ENV["PROFILE_ADHOC"],
      output_path: "fastlane/certs"
    )

    build_app(
      scheme: "CovidShield",
      workspace: "./ios/CovidShield.xcworkspace",
      export_method: "ad-hoc",
      output_directory: "./build",
      export_options: {
        provisioningProfiles: {
          ENV["APP_ID_IOS"] => ENV["PROFILE_ADHOC"]
        }
      }
    )
  end
end

platform :android do
  private_lane :build do |options|
    task = (options[:bundle] ? "bundle" : "assemble")
    properties = (options[:properties] ? options[:properties] : {})
    buildType = (options[:buidType] ? options[:buildType] : "Release")

    gradle(
      task: task,
      build_type: buildType,
      project_dir: 'android/',
      properties: properties
    )
  end

  desc "Pushes a new build to Google Play Internal Testing Track"
  lane :internal do
    ensure_git_branch

    versionCode = ENV["APP_VERSION_CODE"]
    versionName = "#{ENV['APP_VERSION_NAME']} (#{ENV['APP_VERSION_CODE']})"

    build(bundle: true, properties: {
        'versionCode' => versionCode,
        'versionName' => versionName
      }
    )

    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    )

    create_github_release(platform: "Android")
  end

  desc "Builds a local .apk for Android"
  lane :local do
    build
  end
end
